title: Exploratory Data Analysis
logo: /assets/img/eda.jpg
description: 
  <p align="left">
  <a href="https://github.com/jtkSource">GitHub</a>
 
  <br>   
   Notes on Exploratory Data Analysis.
  <br>
  </p>
theme: jekyll-theme-minimal
